//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingwaytek.TrafficFlow.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestigaionData
    {
        public int Id { get; set; }
        public int InvestigationId { get; set; }
        public string Intersection { get; set; }
        public string Direction { get; set; }
        public int Amount { get; set; }
        public int TargetType { get; set; }
        public string HourlyInterval { get; set; }
        public Nullable<int> FirstQuarterCount { get; set; }
        public Nullable<int> SecondQuarterCount { get; set; }
        public Nullable<int> ThirdQuarterCount { get; set; }
        public Nullable<int> FourthQuarterCount { get; set; }
    
        public virtual Investigaion Investigaion { get; set; }
    }
}
