//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingwaytek.TrafficFlow.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Investigation()
        {
            this.InvestigationData = new HashSet<InvestigationData>();
        }
    
        public int Id { get; set; }
        public int InvestigationType { get; set; }
        public int PositioningId { get; set; }
        public string PositioningCity { get; set; }
        public string PositioningTown { get; set; }
        public string PositioningRoad1 { get; set; }
        public string PositioningRoad2 { get; set; }
        public decimal PositioningLatitude { get; set; }
        public decimal PositioningLongitude { get; set; }
        public string Positioning { get; set; }
        public string IntersectionId { get; set; }
        public string Weather { get; set; }
        public System.DateTime InvestigaionTime { get; set; }
        public string TrafficControlNote { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public bool Deleted { get; set; }
        public bool Enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestigationData> InvestigationData { get; set; }
    }
}
