
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kingwaytek.TrafficFlow.Repositories
{

using System;
    using System.Collections.Generic;
    
public partial class Positioning
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Positioning()
    {

        this.Investigation = new HashSet<Investigation>();

    }


    public int Id { get; set; }

    public int InvestigationType { get; set; }

    public string City { get; set; }

    public string Town { get; set; }

    public string Road1 { get; set; }

    public string Road2 { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public string Positioning1 { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Investigation> Investigation { get; set; }

}

}
